# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import get_image_encode_pb2 as get__image__encode__pb2


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DlEmbeddingGet = channel.unary_unary(
                '/aiservice.AiService/DlEmbeddingGet',
                request_serializer=get__image__encode__pb2.DlEmbeddingRequest.SerializeToString,
                response_deserializer=get__image__encode__pb2.Tensor.FromString,
                )


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DlEmbeddingGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DlEmbeddingGet': grpc.unary_unary_rpc_method_handler(
                    servicer.DlEmbeddingGet,
                    request_deserializer=get__image__encode__pb2.DlEmbeddingRequest.FromString,
                    response_serializer=get__image__encode__pb2.Tensor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiservice.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DlEmbeddingGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aiservice.AiService/DlEmbeddingGet',
            get__image__encode__pb2.DlEmbeddingRequest.SerializeToString,
            get__image__encode__pb2.Tensor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
